// demo/svelte/src/lib/GlassCanvas.svelte
<script lang="ts">
    /**
     * @file GlassCanvas.svelte
     * @brief Svelte canvas lifecycle and backdrop component.
     * @details Descendant shapes share one renderer; the canvas sizes to the viewport or its container.
     */

    import { onMount, setContext, untrack, type Snippet } from "svelte";
    import { createGlass, DEFAULT_CHROMATIC_ABERRATION, type Appearance, type Fit, type Follow, type StackingMode } from "glassrender";
    import { CANVAS_KEY, type CanvasState } from "./context.js";

    /** @brief Canvas placement, backdrop and environment options for descendant glass components. */
    interface Props {
        /** @brief Picture behind the glass: a URL, or an image, canvas, video or bitmap. */
        backdrop?: string | TexImageSource | null;
        /** @brief How a backdrop of another size is laid on the canvas (default "cover"). */
        fit?: Fit;
        /** @brief Upload the backdrop on every frame (a playing video, an animated canvas). */
        live?: boolean;
        /**
         * @brief Default surroundings of the glass (default "auto": the page's color scheme).
         */
        appearance?: Appearance;
        /** @brief Glass over glass: "exact" (default) or "flat". */
        stacking?: StackingMode;
        /** @brief Turn of the rim lights in radians, clockwise. */
        lightAngle?: number;
        /** @brief Default color-separation multiplier (0..1, default 0.25). */
        chromaticAberration?: number;
        /** @brief Upper limit of device pixels per CSS pixel (default 2). */
        maxPixelRatio?: number;
        /**
         * @brief The window is the active one (default true). false gives the flatter glass of an
         * inactive window; "auto" follows the focus of the page.
         */
        active?: Follow;
        /**
         * @brief The more opaque, more saturated variant of the standard material (default false).
         */
        tinted?: boolean;
        /**
         * @brief Nearly opaque glass without refraction; "auto" (default) follows
         * `prefers-reduced-transparency`.
         */
        reduceTransparency?: Follow;
        /**
         * @brief A stronger, more opaque tone; "auto" (default) follows `prefers-contrast: more`.
         */
        increaseContrast?: Follow;
        /**
         * @brief No refraction inside the glass and more blur; "auto" (default) follows
         * `prefers-reduced-motion: reduce`.
         */
        reduceMotion?: Follow;
        /**
         * @brief Rim lights drawn as a plain outline instead of shaded bands (default false).
         */
        buttonShapes?: boolean;
        /**
         * @brief Draw in extended range on screens that show values above the standard white
         * (default false; "auto" follows `dynamic-range: high`).
         * @details It can change later only when it was true or "auto" when the canvas was made.
         */
        extendedRange?: Follow;
        /**
         * @brief Brightest value of the screen relative to the standard white, used with extended
         * range (default 2).
         */
        headroom?: number;
        /** @brief Preferred brightness multiplier name; overrides headroom when supplied. */
        displayHeadroom?: number;
        /** @brief The canvas covers the viewport (default) or only this element. */
        fixed?: boolean;
        /** @brief Class of the outer element. */
        class?: string;
        /** @brief Called when the browser cannot draw the glass (no WebGL2). */
        onerror?: (message: string) => void;
        /**
         * @brief Called when the WebGL context is lost; the glass draws again on its own when it is
         * back.
         */
        oncontextlost?: () => void;
        /**
         * @brief Called when the context is back: "" when the glass was rebuilt, else why it could
         * not be.
         */
        oncontextrestored?: (error: string) => void;
        children?: Snippet;
    }

    let {
        backdrop = null, fit = "cover", live = false, appearance = "auto", stacking = "exact", lightAngle = 0, chromaticAberration = DEFAULT_CHROMATIC_ABERRATION,
        maxPixelRatio = 2, active = true, tinted = false, reduceTransparency = "auto", increaseContrast = "auto",
        reduceMotion = "auto", buttonShapes = false, extendedRange = false, headroom = 2, displayHeadroom, fixed = true, class: className = "", onerror,
        oncontextlost, oncontextrestored, children
    }: Props = $props();

    const state: CanvasState = $state({ glass: null, error: "" });
    setContext(CANVAS_KEY, state);
    let canvas: HTMLCanvasElement;

    onMount(() => {
        const made = createGlass(canvas, untrack(() => ({
            appearance, stacking, lightAngle, chromaticAberration, maxPixelRatio, extendedRange, headroom: displayHeadroom ?? headroom,
            environment: { active, tinted, reduceTransparency, increaseContrast, reduceMotion, buttonShapes },
            onContextLost: () => oncontextlost?.(),
            onContextRestored: (error: string) => oncontextrestored?.(error)
        })));
        if (!made.ok) {
            state.error = made.error;
            onerror?.(made.error);
            return;
        }
        const glass = made.value;
        state.glass = glass;
        return () => {
            state.glass = null;
            glass.destroy();
        };
    });

    $effect(() => {
        const a = appearance;
        untrack(() => state.glass?.setAppearance(a));
    });
    $effect(() => {
        const s = stacking;
        untrack(() => state.glass?.setStacking(s));
    });
    $effect(() => {
        const a = lightAngle;
        untrack(() => state.glass?.setLightAngle(a));
    });
    $effect(() => {
        const strength = chromaticAberration;
        untrack(() => state.glass?.setChromaticAberration(strength));
    });
    $effect(() => {
        const e = { active, tinted, reduceTransparency, increaseContrast, reduceMotion, buttonShapes };
        untrack(() => state.glass?.setEnvironment(e));
    });
    $effect(() => {
        const on = extendedRange, h = displayHeadroom ?? headroom;
        untrack(() => state.glass?.setExtendedRange(on, h));
    });
    $effect(() => {
        const glass = state.glass, b = backdrop, f = fit, l = live;
        if (glass === null) return;
        if (typeof b === "string") {
            const img = new Image();
            img.crossOrigin = "anonymous";
            img.src = b;
            glass.setBackdrop(img, f, false);
        } else glass.setBackdrop(b, f, l);
    });
</script>

<div class="glass-canvas {className}" class:fixed>
    <canvas bind:this={canvas}></canvas>
    {@render children?.()}
</div>

<style>
    .glass-canvas {
        position: relative;
        isolation: isolate;
    }
    canvas {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        display: block;
        z-index: -1;
        pointer-events: none;
    }
    .fixed > canvas {
        position: fixed;
        width: 100vw;
        height: 100vh;
    }
</style>

// demo/solid/src/GlassCanvas.tsx
import { createEffect, createSignal, onMount, onCleanup, splitProps, type JSX } from "solid-js";
import { createGlass, DEFAULT_CHROMATIC_ABERRATION, type Glass as CoreGlass, type Appearance, type Fit, type Follow, type StackingMode } from "glassrender";
import { CanvasContext, ensureStyle, type CanvasState } from "./context.js";

export interface GlassCanvasProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "onError" | "onContextLost" | "onContextRestored"> {
    backdrop?: string | TexImageSource | null;
    fit?: Fit;
    live?: boolean;
    appearance?: Appearance;
    stacking?: StackingMode;
    lightAngle?: number;
    chromaticAberration?: number;
    /** Creation-time pixel ratio limit. */
    maxPixelRatio?: number;
    active?: Follow;
    tinted?: boolean;
    reduceTransparency?: Follow;
    increaseContrast?: Follow;
    reduceMotion?: Follow;
    buttonShapes?: boolean;
    /** Enable at creation to allow later extended-range changes. */
    extendedRange?: Follow;
    headroom?: number;
    displayHeadroom?: number;
    fixed?: boolean;
    onError?: (message: string) => void;
    onContextLost?: () => void;
    onContextRestored?: (error: string) => void;
}

const COVER: JSX.CSSProperties = { position: "absolute", inset: 0, width: "100%", height: "100%", display: "block", "z-index": -1, "pointer-events": "none" };
const FIXED: JSX.CSSProperties = { ...COVER, position: "fixed", width: "100vw", height: "100vh" };

export function GlassCanvas(props: GlassCanvasProps): JSX.Element {
    const [local, dom] = splitProps(props, ["children", "class", "style", "backdrop", "fit", "live", "appearance", "stacking", "lightAngle", "chromaticAberration", "maxPixelRatio",
        "active", "tinted", "reduceTransparency", "increaseContrast", "reduceMotion", "buttonShapes", "extendedRange", "headroom", "displayHeadroom", "fixed", "onError", "onContextLost", "onContextRestored"]);
    let canvas!: HTMLCanvasElement;
    const [glass, setGlass] = createSignal<CoreGlass | null>(null), [error, setError] = createSignal("");
    const state: CanvasState = { get glass() { return glass(); }, get error() { return error(); } };
    onMount(() => {
        ensureStyle();
        const made = createGlass(canvas, {
            appearance: local.appearance ?? "auto", stacking: local.stacking ?? "exact", lightAngle: local.lightAngle ?? 0,
            chromaticAberration: local.chromaticAberration ?? DEFAULT_CHROMATIC_ABERRATION, maxPixelRatio: local.maxPixelRatio ?? 2,
            extendedRange: local.extendedRange ?? false, displayHeadroom: local.displayHeadroom ?? local.headroom ?? 2,
            environment: { active: local.active ?? true, tinted: local.tinted ?? false, reduceTransparency: local.reduceTransparency ?? "auto",
                increaseContrast: local.increaseContrast ?? "auto", reduceMotion: local.reduceMotion ?? "auto", buttonShapes: local.buttonShapes ?? false },
            onContextLost: () => local.onContextLost?.(), onContextRestored: message => local.onContextRestored?.(message)
        });
        if (!made.ok) { setError(made.error); local.onError?.(made.error); return; }
        const instance = made.value;
        setGlass(instance);
        onCleanup(() => { setGlass(null); instance.destroy(); });
    });
    createEffect(() => { glass()?.setAppearance(local.appearance ?? "auto"); });
    createEffect(() => { glass()?.setStacking(local.stacking ?? "exact"); });
    createEffect(() => { glass()?.setLightAngle(local.lightAngle ?? 0); });
    createEffect(() => { glass()?.setChromaticAberration(local.chromaticAberration ?? DEFAULT_CHROMATIC_ABERRATION); });
    createEffect(() => { glass()?.setExtendedRange(local.extendedRange ?? false, local.displayHeadroom ?? local.headroom ?? 2); });
    createEffect(() => { glass()?.setEnvironment({ active: local.active ?? true, tinted: local.tinted ?? false,
        reduceTransparency: local.reduceTransparency ?? "auto", increaseContrast: local.increaseContrast ?? "auto",
        reduceMotion: local.reduceMotion ?? "auto", buttonShapes: local.buttonShapes ?? false }); });
    createEffect(() => {
        const instance = glass(), source = local.backdrop ?? null, fit = local.fit ?? "cover", live = local.live ?? false;
        if (!instance) return;
        if (typeof source === "string") {
            const image = new Image(); image.crossOrigin = "anonymous"; image.src = source;
            instance.setBackdrop(image, fit, false);
        } else instance.setBackdrop(source, fit, live);
    });
    const style = (): JSX.CSSProperties | string => typeof local.style === "string"
        ? "position:relative;isolation:isolate;" + local.style : { position: "relative", isolation: "isolate", ...local.style };
    return <div {...dom} class={"glass-canvas" + (local.class ? " " + local.class : "")} style={style()}>
        <canvas ref={canvas} style={local.fixed === false ? COVER : FIXED} />
        <CanvasContext.Provider value={state}>{local.children}</CanvasContext.Provider>
    </div>;
}
